### PR TITLE
Refactor atomic operations by using internal implementation

### PR DESCRIPTION
**Pull request by luckyxiaoqiang**
### Describe what this PR does / why we need it
Refactor atomic operations by using internal implementation.

### Special notes for reviews

### CODE REVIEW

**Comment by louyuting** [comment]
Could you please resolve the CI?

**Comment by luckyxiaoqiang** [comment]
> Could you please resolve the CI?

Although I have read the details of check result, but I cannot find out where goes wrong. Would you help me? Or just give some hint?

**Comment by luckyxiaoqiang** [comment]
> > Could you please resolve the CI?
> 
> Although I have read the details of check result, but I cannot find out where goes wrong. Would you help me? Or just give some hint?

Addressed.

**Review by louyuting — APPROVED** [review]
Thanks for your nice work

**Pull request merged**
