### PR TITLE
Fix integer overflow on 32-bit platform

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

### Describe what this PR does / why we need it

Fix https://github.com/dapr/components-contrib/issues/1033

### Special notes for reviews

### CODE REVIEW

**Comment by daixiang0** [comment]
@sczyh30 please review

**Comment by sczyh30** [comment]
Hi, could you please reformat your code?

**Comment by daixiang0** [comment]
@sczyh30 done.

**Comment by daixiang0** [comment]
ping @sczyh30

**Comment by sczyh30** [comment]
It seems that the linter check failed: https://github.com/alibaba/sentinel-golang/pull/422/checks?check_run_id=3177687857

**Comment by daixiang0** [comment]
@sczyh30 I use force covert, please review

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by daixiang0** [comment]
@sczyh30 thanks for the review, when is the next release?

**Comment by sczyh30** [comment]
Thanks for contributing!

**Comment by sczyh30** [comment]
> @sczyh30 thanks for the review, when is the next release? Or a bugfix version?

Maybe next week. cc @louyuting @sanxun0325 @luckyxiaoqiang

**Comment by sczyh30** [comment]
Hi, v1.0.3 has been released: https://github.com/alibaba/sentinel-golang/releases/tag/v1.0.3

**Comment by daixiang0** [comment]
cool!

**Pull request merged**
