### PR TITLE
Rule Manager: flow module supports resource level replacement

### PR DESCRIPTION
**Pull request by louyuting**
### Describe what this PR does / why we need it
flow module supports resource level replacement

### Special notes for reviews

### CODE REVIEW

**Comment by louyuting** [comment]
@sanxun0325 @sczyh30  Could you please review this PR?

**Review by sanxun0325 — APPROVED** [review]
LGTM

**Comment by louyuting** [comment]
> LGTM

We might need pend this PR B/C the #200 
Statistic reuse need be consideration

**Comment by louyuting** [comment]
Will refile another pr to implement

**Pull request closed without merging**
