### PR TITLE
Add unit test for flow control

### PR DESCRIPTION
**Pull request by zsy619**
### Describe what this PR does / why we need it

Code path: core/flow/*
Target coverage: 50+% statements.
Fix: #45
### Special notes for reviews
go test -v -race ./.  -cover
=== RUN   TestSetAndRemoveTrafficShapingGenerator
--- PASS: TestSetAndRemoveTrafficShapingGenerator (0.00s)
=== RUN   TestIsValidFlowRule
--- PASS: TestIsValidFlowRule (0.00s)
=== RUN   TestFlowRule_ResourceName
=== RUN   TestFlowRule_ResourceName/test1
=== RUN   TestFlowRule_ResourceName/test2
--- PASS: TestFlowRule_ResourceName (0.00s)
    --- PASS: TestFlowRule_ResourceName/test1 (0.00s)
    --- PASS: TestFlowRule_ResourceName/test2 (0.00s)
=== RUN   TestFlowRule_String
=== RUN   TestFlowRule_String/test1
--- PASS: TestFlowRule_String (0.00s)
    --- PASS: TestFlowRule_String/test1 (0.00s)
=== RUN   TestFlowRule_LoadFromJson
--- PASS: TestFlowRule_LoadFromJson (0.00s)
=== RUN   TestDefaultTrafficShapingCalculator_CalculateAllowedTokens
=== RUN   TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test1
=== RUN   TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test2
=== RUN   TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test3
=== RUN   TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test4
=== RUN   TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test5
--- PASS: TestDefaultTrafficShapingCalculator_CalculateAllowedTokens (0.00s)
    --- PASS: TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test1 (0.00s)
    --- PASS: TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test2 (0.00s)
    --- PASS: TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test3 (0.00s)
    --- PASS: TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test4 (0.00s)
    --- PASS: TestDefaultTrafficShapingCalculator_CalculateAllowedTokens/test5 (0.00s)
=== RUN   TestDefaultTrafficShapingChecker_DoCheck
=== RUN   TestDefaultTrafficShapingChecker_DoCheck/test1_0
=== RUN   TestDefaultTrafficShapingChecker_DoCheck/test1_1
=== RUN   TestDefaultTrafficShapingChecker_DoCheck/test2_0
=== RUN   TestDefaultTrafficShapingChecker_DoCheck/test2_1
=== RUN   TestDefaultTrafficShapingChecker_DoCheck/test2_2
--- PASS: TestDefaultTrafficShapingChecker_DoCheck (0.00s)
    --- PASS: TestDefaultTrafficShapingChecker_DoCheck/test1_0 (0.00s)
    --- PASS: TestDefaultTrafficShapingChecker_DoCheck/test1_1 (0.00s)
    --- PASS: TestDefaultTrafficShapingChecker_DoCheck/test2_0 (0.00s)
    --- PASS: TestDefaultTrafficShapingChecker_DoCheck/test2_1 (0.00s)
    --- PASS: TestDefaultTrafficShapingChecker_DoCheck/test2_2 (0.00s)
=== RUN   TestThrottlingChecker_DoCheckNoQueueingSingleThread
--- PASS: TestThrottlingChecker_DoCheckNoQueueingSingleThread (0.21s)
=== RUN   TestThrottlingChecker_DoCheckSingleThread
--- PASS: TestThrottlingChecker_DoCheckSingleThread (0.00s)
=== RUN   TestThrottlingChecker_DoCheckQueueingParallel
--- PASS: TestThrottlingChecker_DoCheckQueueingParallel (0.00s)
=== RUN   TestTrafficShapingController_Rule
=== RUN   TestTrafficShapingController_Rule/test1
--- PASS: TestTrafficShapingController_Rule (0.00s)
    --- PASS: TestTrafficShapingController_Rule/test1 (0.00s)
=== RUN   TestTrafficShapingController_FlowChecker
=== RUN   TestTrafficShapingController_FlowChecker/test1
--- PASS: TestTrafficShapingController_FlowChecker (0.00s)
    --- PASS: TestTrafficShapingController_FlowChecker/test1 (0.00s)
=== RUN   TestTrafficShapingController_PerformChecking
=== RUN   TestTrafficShapingController_PerformChecking/test1
=== RUN   TestTrafficShapingController_PerformChecking/test2
--- PASS: TestTrafficShapingController_PerformChecking (0.00s)
    --- PASS: TestTrafficShapingController_PerformChecking/test1 (0.00s)
    --- PASS: TestTrafficShapingController_PerformChecking/test2 (0.00s)
=== RUN   TestTrafficShapingController_FlowCalculator
=== RUN   TestTrafficShapingController_FlowCalculator/test1
--- PASS: TestTrafficShapingController_FlowCalculator (0.00s)
    --- PASS: TestTrafficShapingController_FlowCalculator/test1 (0.00s)
PASS
coverage: 62.6% of statements
ok      github.com/sentinel-group/sentinel-golang/core/flow     (cached)        coverage: 62.6% of statements

### CODE REVIEW

**Comment by louyuting** [comment]
Hi, CI indicate the error.
Could you please fix it?
In addition, you might need to rebase your repo from alibaba/sentinel-golang master branch.

Thanks.

**Comment by zsy619** [comment]
@louyuting 帮忙看下，是哪里问题，本机测试正常

**Comment by zsy619** [comment]
以前的commit也集成到这个pr里面了，什么问题

**Comment by zsy619** [comment]
image
红色是本次要合并内容

**Comment by zsy619** [comment]
错误，删除

**Comment by louyuting** [comment]
最佳实践来说：
1. 最好一个Pull Request 你单独拉一个分支，然后pull request 到 alibaba/sentinel-golang的master分支
2. 每次你的新分支的代码，在pull request到alibaba/sentinel-golang的master分支之前，先rebase一下alibaba/sentinel-golang的master分支最新的代码。确保diff只有你本次提交的代码。

**Pull request closed without merging**
