### PR TITLE
Add result token pool  (#137)

### PR DESCRIPTION
**Pull request by NineSunRD**
### Describe what this PR does / why we need it
I want to modify the original code as little as possible, but now it exists a lot of temporary token result, so my modify will look very ugly, as shown below。
image

### Does this pull request fix one issue?
#137 

### Special notes for reviews

### CODE REVIEW

**Comment by louyuting** [comment]
The CI build failed. Could you please fix it?

**Comment by sczyh30** [comment]
Thanks for contributing! However this seems not elegant enough and may bring boilerplate code. We need to open a new issue to improve this.

**Comment by sczyh30** [comment]
And looking forward to more contributions :)

**Comment by louyuting** [comment]
> Thanks for contributing! However this seems not elegant enough and may bring boilerplate code. We need to open a new issue to improve this.

Yes, It should be improve.

**Comment by NineSunRD** [comment]
Yes, I think so, I have seen the new issue, I will try to contribute it。

**Pull request merged**
