### PR TITLE
update args of golangci-lint in ci.yml

### PR DESCRIPTION
**Pull request by jnan806**
### Describe what this PR does / why we need it
update args of golangci-lint in ci.yml according to official guides

### Describe how you did it
according to comment of https://github.com/golangci/golangci-lint-action/issues/618#issuecomment-1587781568
relation pr https://github.com/golangci/golangci-lint-action/pull/769

### Special notes for reviews

### CODE REVIEW

**Comment by sczyh30** [comment]
Could you please sync with the latest master branch? We've fixed other CI failures.

**Comment by jnan806** [comment]
> Could you please sync with the latest master branch? We've fixed other CI failures.

done

**Review by sczyh30 — APPROVED** [review]
LGTM

**Comment by sczyh30** [comment]
Thanks!

**Pull request merged**
