### PR TITLE
Optimize logging debug by level pre-check

### PR DESCRIPTION
**Pull request by luckyxiaoqiang**
### Describe what this PR does / why we need it
Optimize logging debug by level pre-check.  

In product environment, the log level usually is `info` or `warn`. Although the debug log does not output, there is still a non-negligible overhead. These include the overhead of parameter evaluation, the overhead of converting parameter to interface.

We can briefly compare the performance data before and after optimization.  
```
Benchmark_LoggingDebug_Without_Precheck-4   	21814083	        46.1 ns/op	      64 B/op	       1 allocs/op
Benchmark_LoggingDebug_With_Precheck-4      	614680490	         1.76 ns/op	       0 B/op	       0 allocs/o
``` 

### Special notes for reviews

### CODE REVIEW

**Comment by louyuting** [comment]
Hi, your idea is great. the parameters pass exists overhead.

Could you please join dingding group: 23339422 to discuss more detail? Besides please attach your github id for identification.

Thanks

**Comment by luckyxiaoqiang** [comment]
> Hi, your idea is great. the parameters pass exists overhead.
> 
> Could you please join dingding group: 23339422 to discuss more detail? Besides please attach your github id for identification.
> 
> Thanks

 Glad to do. I have sent the join request. Expect more communication.

**Comment by louyuting** [comment]
Hi, @luckyxiaoqiang  your idea is great!
From my perspective, wrap all logging.Debug() might be too fat. We could wrap only the Debug log in the Entry main process.

**Comment by luckyxiaoqiang** [comment]
> Hi, @luckyxiaoqiang your idea is great!
> From my perspective, wrap all logging.Debug() might be too fat. We could wrap only the Debug log in the Entry main process.

Agree. I'll adjust.

**Review by louyuting — APPROVED** [review]
Thanks for contribution

**Review by sczyh30 — APPROVED** [review]

**Comment by sczyh30** [comment]
Thanks for contributing and look forward to more!

**Pull request merged**
