### PR TITLE
Migrate CI to Github Actions.

### PR DESCRIPTION
**Pull request by sdttttt**
### Describe what this PR does / why we need it

In my observation, under the same build conditions, 
the speed on GithubActions is at least twice as 🚀fast as that of TravisCI.

I recommend moving from TravisCI to Github Actions.

### Special notes for reviews

### CODE REVIEW

**Comment by sdttttt** [comment]
Please check to the CI behavior has **changed**.

**Comment by louyuting** [comment]
Hi, could you please resolve the conflict?

**Comment by louyuting** [comment]
Besides, 
image
Ci seems not be triggered?

**Comment by sdttttt** [comment]
> Ci seems not be triggered?

If only the configuration files such as `.GitHub / `and `travis.yml` are modified, TravisCI may not trigger...

**Comment by sdttttt** [comment]
It's really strange...
Why there is no way to pass the construction of go 1.12.

**Comment by sdttttt** [comment]
PTAL. It looks much better. @louyuting

**Review by louyuting — DISMISSED** [review]
Thanks for contribution

**Review by louyuting — APPROVED** [review]
Thanks for contribution

**Pull request merged**
